version: '3.7'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: written_root_password
      MYSQL_DATABASE: written_waffle
      MYSQL_USER: written-waffle
      MYSQL_PASSWORD: toyproject
  test-db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
volumes:
  db_data: {}
