# Generated by Django 3.1 on 2021-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20210101_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
